# -*- coding: utf-8 -*-
"""2nd_class-HW

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DhyC7umz60sei7ZMpG15WQEvLUmLUGNy
"""

#creating variables
name="Tawhid"
age = 22
favourite_color = "Blue"
print("Name:",name)
print("Age:",age)
print("Favourite color:",favourite_color)

#creating variables in each type
name= "Rahim"
age = 80
price= 199.99
has_paid = True
result = None
print(type(name))
print(type(age))
print(type(price))
print(type(has_paid))
print(type(result))

l=7
w=5
print("Area:",l*w)
print("perimeter:",2*(l+w))

fruits = ["Mango", "Jackfruit", "Banana", "Litchi", "Guava"]
print(fruits[0])
print(fruits[-1])

# List of five numbers
numbers = [12, 5, 30, 18, 7]
numbers.append(25)
numbers.remove(18)

numbers.sort()
print(numbers)

student = {
"name": "Tawhid",
"age": 22,
"university": "KU",
"courses": ["Data Science"]}

location = (21.4272, 92.0058)

from typing import Union
# Two sets of colors
set1 = {"red", "blue", "green"}
set2 = {"green", "yellow", "blue"}

Union = set1 | set2
print(Union)
common = set1 & set2
print(common)

def print_first_last():
    s = input("Enter a string: ")

    if len(s) == 0:
        print("Empty string")
    else:
        print("First character:", s[0])
        print("Last character:", s[-1])
print_first_last()

def print_uppercase():
   s= input("Enter a string: ")
   print(s.upper())
print_uppercase()